Evaluation
Jakyln/ipi-java-350-ex pull request #1
Opened 2022-06-21 14:03 UTC by Jakyln

Travail en cours

2022-06-24 16:04 UTC, ArthisC commented on src/main/java/com/ipiecoles/java/java350/model/Employe.java
> +        if(this.salaire != null){
attention tu ne gère pas les pourcentages négatif ou égale à 0 
`if( 0d < pourcentage && pourcentage < 1d)`

2022-06-24 16:14 UTC, ArthisC commented on src/test/java/com/ipiecoles/java/java350/Integration/EmployeServiceIntegrationTest.java
> +
Quand on fais des test il vaut mieux clear la bdd entre chaque test pour ne pas dépendre des test précédent comme c'est le cas pour ton testAvgPerformanceWhereMatriculeStartsWith
`@BeforeEach
    public void delete(){
        employeRepository.deleteAll();
    }`

2022-06-24 16:18 UTC, ArthisC requested changes
Bon code mais quelque remarque quand même.

2022-06-24 16:24 UTC, ArthisC requested changes

2022-06-24 16:24 UTC, ArthisC commented on src/main/java/com/ipiecoles/java/java350/model/Employe.java
> +            if(pourcentage < 1d){
```suggestion
            if( 0d < pourcentage && pourcentage < 1d){
```

2022-06-24 16:24 UTC, ArthisC commented on src/test/java/com/ipiecoles/java/java350/model/EmployeTest.java
> +
ajouter un test avec un pourcentage négatif

2022-07-19 14:13 UTC, pjvilloud reviewed
Acquis. Les bases sont bien comprises, il manque des exercices dans le rendu.

2022-07-19 14:13 UTC, pjvilloud commented on src/main/java/com/ipiecoles/java/java350/model/Employe.java
> +        nbJoursRTT = (nbJoursTotal - Entreprise.NB_JOURS_MAX_FORFAIT - nbJoursWeekend - Entreprise.NB_CONGES_BASE - nbJoursFeriesHorsWeekend) * tempsPartiel;
Très bon refactoring

2022-07-19 14:13 UTC, pjvilloud commented on src/test/java/com/ipiecoles/java/java350/Integration/EmployeServiceIntegrationTest.java
> +        Double performance = employeRepository.avgPerformanceWhereMatriculeStartsWith("C");
A mettre dans EmployeRepositoryTest

2022-07-19 14:13 UTC, pjvilloud commented on src/test/java/com/ipiecoles/java/java350/Integration/EmployeServiceIntegrationTest.java
> +
Ou est le test d'intégration ?

2022-07-19 14:13 UTC, pjvilloud commented on src/test/java/com/ipiecoles/java/java350/service/EmployeServiceTest.java
> +                .hasMessage("Limite des 100000 matricules atteinte !");*/
OK pour ce cas mais il en manque beaucoup d'autre !!

2023-10-16 07:40 UTC, closed without merging